version: '3'
services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "8081:8081"

  order-service:
    build:
      context: ./order-service
    ports:
      - "8082:8082"
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

